### ISSUE TITLE
Large fire returning unexpected results

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/nldi_polygon_query#3]
Issue related to https://github.com/USGS-WiM/StreamStats-National/pull/193

I queried this fire near Honey Lake, CA 

![image](https://user-images.githubusercontent.com/40237491/174156668-2b59d603-513a-4df9-a2f2-95d2a394d2fd.png)

The fire (red polygon) is very large. Only a small part of the fire has results returned from the nldi_polygon_query endpoint.

[payload.json](https://files.slack.com/files-pri/T2PFUSXUL-F03KUD2CR3Q/download/payload.json?origin_team=T2PFUSXUL)
[response.json](https://files.slack.com/files-pri/T2PFUSXUL-F03L11HN7RQ/download/response.json?origin_team=T2PFUSXUL)

**Comment by Anders-Hopkins** [comment]
I updated the repo based off of suggestions from Aaron (enforced PEP8, cleaned up some unnecessary variables and if statements) pushed these changes to the server and restarted. I doubt that these changes will help to solve this problem.

**Comment by amedenblik** [comment]
Confirmed that the changes didn't solve the problem. The results look similar.

**Comment by Anders-Hopkins** [comment]
Dang! I am making the request from my machine directly to the nldi-poly-query service (rather than an instance of the service running on my machine) and I get the entire response. The query does take 3-5 minutes to run, so maybe that long wait time is tripping up Streamstats somehow. Or the object that gets returned is too large (the json that gets returned from this query is 6.9 MB).

**Comment by Anders-Hopkins** [comment]
@amedenblik I get the entire response when making the request to `https://nldi-polygon-query.streamstats.usgs.gov/nldi_poly_query/` from my laptop so I think that the problem is on the client side of things.
